FROM mcr.microsoft.com/dotnet/core/sdk:2.2
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["src/Default_ContainerApplicationForKubernetes/Default_ContainerApplicationForKubernetes.csproj", "src/Default_ContainerApplicationForKubernetes/"]

RUN dotnet restore "src/Default_ContainerApplicationForKubernetes/Default_ContainerApplicationForKubernetes.csproj"
COPY . .
WORKDIR "/src/src/Default_ContainerApplicationForKubernetes"
RUN dotnet build --no-restore "Default_ContainerApplicationForKubernetes.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]