# base image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic AS runtime

ARG HTTP_PORT=80
ARG APP_HOME=/app

WORKDIR ${APP_HOME}
COPY ["/linux-x64/.", "./"]

ENV HOME ${APP_HOME}
ENV NAME smb-sample

# Make ports available to the world outside this container for main web interface
EXPOSE ${HTTP_PORT}

VOLUME /appdata

ENTRYPOINT ["dotnet", "Docker.TesterWebSite.dll"]
