# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/runtime:9.0-nanoserver-ltsc2025 AS runtime

ARG APP_HOME=/var/app

WORKDIR ${APP_HOME}
COPY ["/bin/Release/net9.0/publish/.", "./"]

ENV HOME ${APP_HOME}
ENV NAME ConsoleAppSample

VOLUME c:/var/appdata

ENTRYPOINT ["dotnet", "ConsoleAppSample.dll"]