version: '3.7'
services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml
    environment:
        - JENKINS_URL=http://jenkins:8080
    ports:
      - '8080:8080'
      - '50000:50000'
    restart: always

volumes:
  jenkins_home:
    external: true
