version: '3.7'
services:

  jenkins:
    #image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
        - JENKINS_USER=admin
        - JENKINS_PASS=admin
        - JENKINS_URL=http://jenkins:8111
    ports:
      - '8111:8080'   #client:server
      - '50000:50000' #client:server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  jenkins_home:
    external: true
