
#+  configure admin center
#+	.net 4.7 sdk
#+	.net 4.8 sdk
#+	7 zip
#+  NuGet
#	.asp.net mvc 5 skd
#.sql cmd tools
#	.net core sdk
#	.VS build tools 2019
# SSRS tools
# pythond
#add bin file environment paths
#limit teamcity memory and cpu
#limit agent memory and cpu
#sql 
#powershell

## paths C:\Program Files\7-Zip

# escape=`
#FROM microsoft/dotnet-framework-build:4.7.1-windowsservercore-ltsc2016  
#SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]


FROM mcr.microsoft.com/dotnet/framework/sdk

# Install 7z
RUN [Net.ServicePointManager]::SecurityProtocol = 'tls12, tls11, tls' ; \
    Invoke-WebRequest https://www.7-zip.org/a/7z1900-x64.msi -OutFile 7z.msi; \
    Start-Process msiexec -Wait -ArgumentList /q, /i, 7z.msi ; \
    Remove-Item -Force 7z.msi

# Install Chocolatey
RUN powershell Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# Install NuGet CLI
RUN powershell choco install nuget.commandline

## Deve
FROM mcr.microsoft.com/dotnet/sdk:3.1
FROM mcr.microsoft.com/dotnet/sdk:5.0


##
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

#

#
#
#SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
#
#
#FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.2

# Install Chocolatey
#RUN @powershell -NoProfile -ExecutionPolicy Bypass -Command "$env:ChocolateyUseWindowsCompression='false'; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
#RUN powershell add-windowsfeature web-asp-net45 \
#&& choco install dotnet4.7 --allow-empty-checksums -y \



# Tools
#FROM mcr.microsoft.com/powershell:latest

# SKDs
#FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
#FROM mcr.microsoft.com/dotnet/core/sdk:2.1
#FROM mcr.microsoft.com/dotnet/core/sdk:3.0
##FROM mcr.microsoft.com/mssql-tools	thats linux
##FROM python

# Install 7z
#RUN [Net.ServicePointManager]::SecurityProtocol = 'tls12, tls11, tls' ; \
    #Invoke-WebRequest https://www.7-zip.org/a/7z1900-x64.msi -OutFile 7z.msi; \
    #Start-Process msiexec -Wait -ArgumentList /q, /i, 7z.msi ; \
    #Remove-Item -Force 7z.msi

# Install 7z
#RUN [Net.ServicePointManager]::SecurityProtocol = 'tls12, tls11, tls' ; \
    #Invoke-WebRequest https://www.7-zip.org/a/7z1900-extra.7z -OutFile 7z.zip; \
    #Expand-Archive 7z.zip -DestinationPath $Env:ProgramFiles\7-Zip ; \
    #Remove-Item -Force 7z.zip


# Path
#RUN setx /M Path "C:\Program Files\7-Zip"