version: '3.8'
services:

  teamcityagent0001:
    image: teamcityagent:1.0.0-windows #will tag it since it used dockerfile
    container_name: teamcityagent0001
    hostname: teamcityagent0001
    volumes:
      - teamcityagent:c:/buildagent/conf
      - teamcityagent:c:/buildagent/logs
    environment:
      - AGENT_NAME="teamcityagent0001"
      - SERVER_URL="http://teamcity:8111"
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=350m"
    expose:
      - 8111
    ports:
      - '9090:9090'   #client:server
    networks:
      - isolated_nw
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  teamcityagent:
    external: true

networks:
  isolated_nw:
    external: true
