version: '3.8'
services:

  teamcityagent0001:
    image: jetbrains/teamcity-agent:latest
    container_name: teamcityagent0001
    hostname: teamcityagent0001
    volumes:
      - teamcityagent0001_data:c:/var/teamcity/teamcityagent0001/conf
      - teamcityagent0001_logs:c:/var/teamcity/teamcityagent0001/
    environment:
      - AGENT_NAME=teamcityagent0001
      - SERVER_URL=http://teamcity:8111/
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
    expose:
      - 8111
    ports:
      - '9090:9090'   #client:server
    restart: always
    networks:
      - isolated_nw
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  teamcityagent0001_data:
    external: true
  teamcityagent0001_logs:
    external: true

networks:
  isolated_nw:
    external: true