version: '3.8'
services:

  teamcityserver:
    image: jetbrains/teamcity-server
    container_name: teamcityserver
    hostname: teamcityserver
    volumes:
      - teamcityserver:/data/teamcity_server/datadir
      - teamcityserver:/opt/teamcity/logs
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xms256m"
    expose:
      - 8111
    ports:
      - '8111:8111'   #client:server
    restart: always
    networks:
      - isolated_nw

volumes:
  teamcityserver:
    external: true
 
networks:
  isolated_nw:
    external: true
