version: '3.7'
services:

  server:
    image: jetbrains/teamcity-server:latest-nanoserver
    container_name: TeamCityServer
    volumes:
      - teamcityserver_data:C:\ProgramData\JetBrains\TeamCity
      - teamcityserver_logs:C:\TeamCity\logs
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx750m"
    ports:
      - '8111:8111'   #client:server
    restart: always

volumes:
  teamcityserver_data:
    external: true
  teamcityserver_logs:
    external: true