FROM mcr.microsoft.com/dotnet/runtime:10.0-nanoserver-ltsc2025 AS runtime
USER $APP_UID
ARG APP_HOME=/app

WORKDIR ${APP_HOME}
COPY ["/ConsoleAppProcessStartSample/.", "./ConsoleAppProcessStartSample/"]
COPY ["/Default_ConsoleApp1/.", "./Default_ConsoleApp1/"]

RUN dir

# Sets the fixed executable process
ENTRYPOINT ["dotnet", "ConsoleAppProcessStartSample/ConsoleAppProcessStartSample.dll"]

# Supplies default arguments that users can override at runtime
CMD ["--environment", "Production"]

### docker build -f Dockerfile.windows --no-cache -t consoleappprocessstartsample .
### docker run -it --rm --name consoleappprocessstartsample consoleappprocessstartsample