FROM mcr.microsoft.com/dotnet/runtime:10.0 AS runtime
USER $APP_UID
ARG APP_HOME=/app

WORKDIR ${APP_HOME}
COPY ["/ConsoleAppProcessStartSample/.", "./ConsoleAppProcessStartSample/"]
COPY ["/Default_ConsoleApp1/.", "./Default_ConsoleApp1/"]

RUN ls -la

# Sets the fixed executable process
ENTRYPOINT ["dotnet", "ConsoleAppProcessStartSample/ConsoleAppProcessStartSample.dll"]

# Supplies default arguments that users can override at runtime
CMD ["--environment", "Production"]

### docker build -f Dockerfile --no-cache -t consoleappprocessstartsample .
### docker run -it --name consoleappprocessstartsample consoleappprocessstartsample